/* Copyright 2019 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#include <stdio.h>
#include <stdlib.h>

int mvin_mvout_main();
int mvin_mvout_zeros_main();
int mvin_mvout_stride_main();
int mvin_mvout_block_stride_main();
int mvin_mvout_acc_main();
int mvin_mvout_acc_zero_stride_main();
int mvin_mvout_acc_stride_main();
int mvin_mvout_acc_full_main();
int mvin_mvout_acc_full_stride_main();
int matmul_os_main();
int matmul_ws_main();
int matmul_main();
int raw_hazard_main();
int aligned_main();
int padded_main();
int mvin_scale_main();
int conv_main();
int conv_with_pool_main();
int conv_with_rot180_main();
int conv_with_kernel_dilation_main();
int conv_with_input_dilation_main();
int conv_with_input_dilation_and_rot180_main();
int conv_with_input_dilation_and_neg_padding_main();
int conv_trans_output_1203_main();
int conv_trans_weight_1203_main();
int conv_trans_weight_0132_main();
int conv_trans_input_3120_main();
int conv_trans_input_3120_with_kernel_dilation_main();
int conv_first_layer_main();
int conv_dw_main();
int tiled_matmul_os_main();
int tiled_matmul_ws_main();
int tiled_matmul_ws_At_main();
int tiled_matmul_ws_Bt_main();
int tiled_matmul_ws_full_C_main();
int tiled_matmul_ws_low_D_main();
int tiled_matmul_cpu_main();
int tiled_matmul_option_main();
int tiled_matmul_ws_perf_main();
int transpose_main();
int matrix_add_main();
int resadd_main();
int global_average_main();
int template_main();
int gemmini_counter_main();
int resnet50_main();
int mobilenet_main();
int transformer_main();
int main() {
    printf("Freedom-e-SDK loaded ...\n");
    printf("Launching Gemmini workloads\n");
    printf("resnet50_main exited with return code %x ...\n",	 resnet50_main());
    printf("mobilenet_main exited with return code %x ...\n",	 mobilenet_main());
    //printf("transformer_main exited with return code %x ...\n",	 transformer_main());
    //printf("mvin_mvout_main exited with return code %x ...\n",	 mvin_mvout_main());
    //printf("mvin_mvout_zeros_main exited with return code %x ...\n",	 mvin_mvout_zeros_main());
    //printf("mvin_mvout_stride_main exited with return code %x ...\n",	 mvin_mvout_stride_main());
    //printf("mvin_mvout_block_stride_main exited with return code %x ...\n",	 mvin_mvout_block_stride_main());
    //printf("mvin_mvout_acc_main exited with return code %x ...\n",	 mvin_mvout_acc_main());
    //printf("mvin_mvout_acc_zero_stride_main exited with return code %x ...\n",	 mvin_mvout_acc_zero_stride_main());
    //printf("mvin_mvout_acc_stride_main exited with return code %x ...\n",	 mvin_mvout_acc_stride_main());
    //printf("mvin_mvout_acc_full_main exited with return code %x ...\n",	 mvin_mvout_acc_full_main());
    //printf("mvin_mvout_acc_full_stride_main exited with return code %x ...\n",	 mvin_mvout_acc_full_stride_main());
    //printf("matmul_os_main exited with return code %x ...\n",	 matmul_os_main());
    //printf("matmul_ws_main exited with return code %x ...\n",	 matmul_ws_main());
    //printf("matmul_main exited with return code %x ...\n",	 matmul_main());
    //printf("raw_hazard_main exited with return code %x ...\n",	 raw_hazard_main());
    //printf("aligned_main exited with return code %x ...\n",	 aligned_main());
    //printf("padded_main exited with return code %x ...\n",	 padded_main());
    //printf("mvin_scale_main exited with return code %x ...\n",	 mvin_scale_main());
printf("conv_main exited with return code %x ...\n",	 conv_main());
printf("conv_with_pool_main exited with return code %x ...\n",	 conv_with_pool_main());
printf("conv_with_rot180_main exited with return code %x ...\n",	 conv_with_rot180_main());
printf("conv_with_kernel_dilation_main exited with return code %x ...\n",	 conv_with_kernel_dilation_main());
printf("conv_with_input_dilation_main exited with return code %x ...\n",	 conv_with_input_dilation_main());
printf("conv_with_input_dilation_and_rot180_main exited with return code %x ...\n",	 conv_with_input_dilation_and_rot180_main());
printf("conv_with_input_dilation_and_neg_padding_main exited with return code %x ...\n",	 conv_with_input_dilation_and_neg_padding_main());
printf("conv_trans_output_1203_main exited with return code %x ...\n",	 conv_trans_output_1203_main());
printf("conv_trans_weight_1203_main exited with return code %x ...\n",	 conv_trans_weight_1203_main());
printf("conv_trans_weight_0132_main exited with return code %x ...\n",	 conv_trans_weight_0132_main());
printf("conv_trans_input_3120_main exited with return code %x ...\n",	 conv_trans_input_3120_main());
printf("conv_trans_input_3120_with_kernel_dilation_main exited with return code %x ...\n",	 conv_trans_input_3120_with_kernel_dilation_main());
printf("conv_first_layer_main exited with return code %x ...\n",	 conv_first_layer_main());
//printf("conv_dw_main exited with return code %x ...\n",	 conv_dw_main());
printf("tiled_matmul_os_main exited with return code %x ...\n",	 tiled_matmul_os_main());
printf("tiled_matmul_ws_main exited with return code %x ...\n",	 tiled_matmul_ws_main());
    printf("tiled_matmul_ws_At_main exited with return code %x ...\n",	 tiled_matmul_ws_At_main());
    printf("tiled_matmul_ws_Bt_main exited with return code %x ...\n",	 tiled_matmul_ws_Bt_main());
printf("tiled_matmul_ws_full_C_main exited with return code %x ...\n",	 tiled_matmul_ws_full_C_main());
    printf("tiled_matmul_ws_low_D_main exited with return code %x ...\n",	 tiled_matmul_ws_low_D_main());
    ////printf("tiled_matmul_cpu_main exited with return code %x ...\n",	 tiled_matmul_cpu_main());
    ////printf("tiled_matmul_option_main exited with return code %x ...\n",	 tiled_matmul_option_main());
printf("tiled_matmul_ws_perf_main exited with return code %x ...\n",	 tiled_matmul_ws_perf_main());
    //printf("transpose_main exited with return code %x ...\n",	 transpose_main());
    //printf("matrix_add_main exited with return code %x ...\n",	 matrix_add_main());
    ////printf("resadd_main exited with return code %x ...\n",	 resadd_main());
    //printf("global_average_main exited with return code %x ...\n",	 global_average_main());
    //printf("template_main exited with return code %x ...\n",	 template_main());
    printf("gemmini_counter_main exited with return code %x ...\n",	 gemmini_counter_main());
printf("Workload Execution completed\n");
while(1);
}
